name: Build and Release

on:
    push:
        branches: [ "master", "develop" ]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x

            - name: Restore tools
              run: dotnet tool restore

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore

            - name: Test
              run: dotnet test --no-build --verbosity normal
    
    release:
        needs: build
        if: ${{ success() }}
        runs-on: ubuntu-latest
        
        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: 8.0.x

            - name: Restore tools
              run: dotnet tool restore

            - name: Restore dependencies
              run: dotnet restore

            - name: Create release build
              run: |
                  dotnet publish --configuration Release \
                    --runtime win-x64 \
                    --self-contained true \
                    /p:PublishSingleFile=true \
                    --output ./artifacts

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: release-artifacts
                  path: ./artifacts
